openapi: 3.0.0
info:
  title: Comment Service API
  description: API for managing comments.
  version: 1.0.0
servers:
  - url: http://localhost:8081

paths:
  /comments:
    get:
      summary: Get all comments
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
    post:
      summary: Create a new comment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201':
          description: Comment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'

components:
  schemas:
    Comment:
      type: object
      properties:
        id:
          type: string
        authorId:
          type: string
        content:
          type: string
        likesCount:
          type: integer
        parentId:
          type: string
        postedAt:
          type: string
          format: date-time
        status:
          type: string
