stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./mvnw clean package -DskipTests

test:
  stage: test
  script:
    - ./mvnw test

deploy:
  stage: deploy
  script:
    - docker-compose up --build -d
